"""Project scaffolder behind ``nexus init``.

Generates a runnable starter project (no web server, no extra dependencies):

    <dir>/nexus.yaml            adapter stack (storage/git/AI provider)
    <dir>/agents/triage-agent.yaml   agent definition with provider pin
    <dir>/workflows/hello.yaml       single-step workflow using that agent

Every emitted file is loadable by the framework (:class:`AdapterRegistry`,
:class:`AgentRegistry`, :class:`YamlWorkflowLoader`) — the test suite
asserts exactly that.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

PROVIDERS = ("opencode", "copilot", "gemini", "codex", "claude", "openai")
STORAGES = ("file", "postgres", "redis")
GIT_PLATFORMS = ("github", "gitlab")

DEFAULTS: dict[str, str] = {
    "project_name": "my-nexus",
    "git_platform": "github",
    "git_repo": "myorg/myrepo",
    "storage": "file",
    "ai_provider": "opencode",
}


def _prompt(label: str, default: str) -> str:
    answer = input(f"{label} [{default}]: ").strip()
    return answer or default


def collect_answers(use_defaults: bool) -> dict[str, str]:
    """Collect scaffold answers interactively, or take defaults with ``--yes``."""
    if use_defaults:
        return dict(DEFAULTS)
    answers: dict[str, str] = {}
    answers["project_name"] = _prompt("Project name", DEFAULTS["project_name"])
    answers["git_platform"] = _prompt(
        f"Git platform ({'/'.join(GIT_PLATFORMS)})", DEFAULTS["git_platform"]
    ).lower()
    answers["git_repo"] = _prompt("Git repo (org/name)", DEFAULTS["git_repo"])
    answers["storage"] = _prompt(
        f"Storage backend ({'/'.join(STORAGES)})", DEFAULTS["storage"]
    ).lower()
    answers["ai_provider"] = _prompt(
        f"AI provider ({'/'.join(PROVIDERS)}, opencode is free)",
        DEFAULTS["ai_provider"],
    ).lower()
    return answers


def _validate(answers: dict[str, str]) -> None:
    if answers["git_platform"] not in GIT_PLATFORMS:
        raise ValueError(f"Unsupported git platform: {answers['git_platform']}")
    if answers["storage"] not in STORAGES:
        raise ValueError(f"Unsupported storage backend: {answers['storage']}")
    if answers["ai_provider"] not in PROVIDERS:
        raise ValueError(f"Unsupported AI provider: {answers['ai_provider']}")
    if "/" not in answers["git_repo"]:
        raise ValueError("git_repo must look like org/name")


def render_files(answers: dict[str, str]) -> dict[str, str]:
    """Render filename -> content for the starter project."""
    provider = answers["ai_provider"]
    model_line = (
        f"\n      model: {answers['ai_model']}"
        if answers.get("ai_model")
        else ""
    )
    nexus_yaml = f"""# Generated by `nexus init` — adapter stack for {answers['project_name']}
storage:
  type: {answers['storage']}
  base_path: ./data
git:
  type: {answers['git_platform']}
  repo: {answers['git_repo']}
ai:
  - type: {provider}{model_line}
"""
    agent_yaml = f"""apiVersion: "nexus-arc/v1"
kind: "Agent"
metadata:
  name: "Triage"
  description: "Starter triage agent for {answers['project_name']}"
  version: "0.1.0"
spec:
  agent_type: "triage"
  provider: "{provider}"
  timeout_seconds: 300
  max_retries: 2
"""
    workflow_yaml = f"""apiVersion: "nexus-arc/v1"
kind: "Workflow"
metadata:
  name: "Hello"
  description: "Starter single-step workflow for {answers['project_name']}"
  version: "0.1.0"
steps:
  - id: "triage"
    name: "Triage request"
    agent_type: "triage"
"""
    return {
        "nexus.yaml": nexus_yaml,
        "agents/triage-agent.yaml": agent_yaml,
        "workflows/hello.yaml": workflow_yaml,
    }


def scaffold_project(target_dir: str | Path, answers: dict[str, str]) -> list[Path]:
    """Write scaffold files under *target_dir*; fail if any already exist."""
    _validate(answers)
    root = Path(target_dir)
    files = render_files(answers)
    existing = [name for name in files if (root / name).exists()]
    if existing:
        raise FileExistsError(f"Refusing to overwrite: {', '.join(existing)}")
    written: list[Path] = []
    for name, content in files.items():
        path = root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written


def run_init(target_dir: str | Path, use_defaults: bool, answers: dict[str, Any] | None = None) -> list[Path]:
    """Collect answers (unless given) and scaffold the project."""
    resolved = dict(answers) if answers else collect_answers(use_defaults)
    for key, default in DEFAULTS.items():
        resolved.setdefault(key, default)
    written = scaffold_project(target_dir, resolved)
    print(f"Scaffolded {resolved['project_name']} in {Path(target_dir).resolve()}:")
    for path in written:
        print(f"  {path}")
    print("Next: load nexus.yaml with AdapterRegistry.from_config(), "
          "agents/ with AgentRegistry, workflows/ with YamlWorkflowLoader.")
    return written
